blank_issues_enabled: false

contact_links:
  - name: Contributing guide
    url: https://github.com/micolous/grpc-asgi-django-demo/blob/main/CONTRIBUTING.md
    about: More information about what's in scope for this demo

  - name: Discussion forum
    url: https://github.com/micolous/grpc-asgi-django-demo/discussions
    about: For questions, ideas, feature requests, showing off what you've built
